FROM php:8.3-fpm
WORKDIR ${WORKDIR}

RUN apt-get -y update && apt-get -y install git unzip rsync

RUN git config --global user.email "user@docker.com"
RUN git config --global user.name "Docker"

ENV TERM xterm-256color

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer
ENTRYPOINT /bin/bash ${WORKDIR}/docker/configs/php/symfony_install.sh

CMD php-fpm
EXPOSE 9000